### ISSUE TITLE
Randomizer always defaults to "Bingo Season 4!" or crashes randomizer app

### ISSUE THREAD

**Issue by cyanCYMK** [Nordgaren/ERBingoRandomizer#9]
When using the application downloaded from [nexusmods](https://www.nexusmods.com/eldenring/mods/6983), running the randomizer always defaults to "Bingo Season 4!" overwriting any seed entered. All new characters default to the same stats and weapons. Running the application downloaded from this repo and trying to generate the randomizer will silently close the randomizer app.

**Comment by Nordgaren** [comment]
There's no randomization in season 4.

**Comment by Nordgaren** [comment]
and this repo doesn't have the season 4 stuff in it. It's just season 2 (first season with a mod)

**Comment by cyanCYMK** [comment]
I just realized this after watching a bingo brawlers VOD. 🤦 Sorry for the trouble!

**Comment by Nordgaren** [comment]
No problem!
